const collator = new Intl.Collator("tr-TR", {
  sensitivity: "base",
  numeric: true
});

const countryNames: Record<string, string> = {
  afghanistan: "Afganistan",
  albania: "Arnavutluk",
  algeria: "Cezayir",
  andorra: "Andorra",
  angola: "Angola",
  argentina: "Arjantin",
  armenia: "Ermenistan",
  asia: "Asya",
  australia: "Avustralya",
  austria: "Avusturya",
  azerbaijan: "Azerbaycan",
  bahrain: "Bahreyn",
  bangladesh: "Bangladeş",
  belarus: "Belarus",
  belgium: "Belçika",
  bolivia: "Bolivya",
  "bosnia and herzegovina": "Bosna Hersek",
  brazil: "Brezilya",
  bulgaria: "Bulgaristan",
  cameroon: "Kamerun",
  canada: "Kanada",
  chile: "Şili",
  china: "Çin",
  colombia: "Kolombiya",
  congo: "Kongo",
  "costa rica": "Kosta Rika",
  croatia: "Hırvatistan",
  cyprus: "Kıbrıs",
  czechia: "Çekya",
  "czech republic": "Çekya",
  denmark: "Danimarka",
  ecuador: "Ekvador",
  egypt: "Mısır",
  england: "İngiltere",
  estonia: "Estonya",
  europe: "Avrupa",
  finland: "Finlandiya",
  france: "Fransa",
  georgia: "Gürcistan",
  germany: "Almanya",
  ghana: "Gana",
  greece: "Yunanistan",
  hungary: "Macaristan",
  iceland: "İzlanda",
  india: "Hindistan",
  indonesia: "Endonezya",
  international: "Uluslararası",
  iran: "İran",
  iraq: "Irak",
  ireland: "İrlanda",
  israel: "İsrail",
  italy: "İtalya",
  italian: "İtalyan",
  japan: "Japonya",
  jordan: "Ürdün",
  kazakhstan: "Kazakistan",
  kosovo: "Kosova",
  "korea republic": "Güney Kore",
  kuwait: "Kuveyt",
  latvia: "Letonya",
  lithuania: "Litvanya",
  luxembourg: "Lüksemburg",
  malaysia: "Malezya",
  malta: "Malta",
  mexico: "Meksika",
  moldova: "Moldova",
  montenegro: "Karadağ",
  morocco: "Fas",
  netherlands: "Hollanda",
  "new zealand": "Yeni Zelanda",
  nigeria: "Nijerya",
  "ivory coast": "Fildişi Sahili",
  "north america": "Kuzey Amerika",
  "north macedonia": "Kuzey Makedonya",
  "northern ireland": "Kuzey İrlanda",
  norway: "Norveç",
  oceania: "Okyanusya",
  oman: "Umman",
  paraguay: "Paraguay",
  peru: "Peru",
  poland: "Polonya",
  portugal: "Portekiz",
  qatar: "Katar",
  romania: "Romanya",
  russia: "Rusya",
  "saudi arabia": "Suudi Arabistan",
  scotland: "İskoçya",
  senegal: "Senegal",
  serbia: "Sırbistan",
  singapore: "Singapur",
  slovakia: "Slovakya",
  slovenia: "Slovenya",
  "south africa": "Güney Afrika",
  "south america": "Güney Amerika",
  "south korea": "Güney Kore",
  spain: "İspanya",
  sweden: "İsveç",
  switzerland: "İsviçre",
  thailand: "Tayland",
  tunisia: "Tunus",
  turkey: "Türkiye",
  turkiye: "Türkiye",
  turkish: "Türk",
  türkiye: "Türkiye",
  ukraine: "Ukrayna",
  "united arab emirates": "Birleşik Arap Emirlikleri",
  "united states": "Amerika Birleşik Devletleri",
  uruguay: "Uruguay",
  usa: "Amerika Birleşik Devletleri",
  uzbekistan: "Özbekistan",
  venezuela: "Venezuela",
  vietnam: "Vietnam",
  wales: "Galler",
  world: "Dünya"
};

export function localizeCountryName(value: string | null | undefined) {
  const cleaned = value?.trim();
  if (!cleaned) return "";
  return countryNames[normalizeName(cleaned)] ?? cleaned;
}

export function compareTr(a: string, b: string) {
  return collator.compare(a, b);
}

export function normalizeName(value: string) {
  return value
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .replace(/[^\p{Letter}\p{Number}]+/gu, " ")
    .trim()
    .toLowerCase();
}
