const statisticLabels = new Map<string, string>([
  ["possession", "Topa sahip olma"],
  ["ball possession", "Topa sahip olma"],
  ["expected goals", "Beklenen gol"],
  ["expected goals (xg)", "Beklenen gol"],
  ["xg", "Beklenen gol"],
  ["expected assists", "Beklenen asist"],
  ["big chances", "Net fırsat"],
  ["big chances created", "Yaratılan net fırsat"],
  ["big chances missed", "Kaçan net fırsat"],
  ["shots", "Şut"],
  ["total shots", "Toplam şut"],
  ["shots total", "Toplam şut"],
  ["shots on target", "İsabetli şut"],
  ["shots on goal", "İsabetli şut"],
  ["shots off target", "İsabetsiz şut"],
  ["blocked shots", "Engellenen şut"],
  ["shots blocked", "Engellenen şut"],
  ["shots inside box", "Ceza sahası içi şut"],
  ["shots outside box", "Ceza sahası dışı şut"],
  ["shots within penalty area", "Ceza sahası içinden şut"],
  ["shots outside penalty area", "Ceza sahası dışından şut"],
  ["shots accuracy", "Şut isabet oranı"],
  ["shot accuracy", "Şut isabet oranı"],
  ["corners", "Korner"],
  ["corner kicks", "Korner"],
  ["free kicks", "Serbest vuruş"],
  ["throw-ins", "Taç"],
  ["throw ins", "Taç"],
  ["goal kicks", "Aut atışı"],
  ["offsides", "Ofsayt"],
  ["fouls", "Faul"],
  ["saves", "Kurtarış"],
  ["goalkeeper saves", "Kaleci kurtarışı"],
  ["passes", "Pas"],
  ["total passes", "Toplam pas"],
  ["successful passes", "Başarılı pas"],
  ["accurate passes", "İsabetli pas"],
  ["passes accurate", "İsabetli pas"],
  ["failed passes", "Başarısız pas"],
  ["passes accuracy", "Pas isabet oranı"],
  ["pass accuracy", "Pas isabet oranı"],
  ["passes own half", "Kendi yarı sahasında pas"],
  ["passes opposition half", "Rakip yarı sahada pas"],
  ["passes into final third", "Son bölgeye pas"],
  ["key passes", "Kilit pas"],
  ["backward passes", "Geri pas"],
  ["long passes", "Uzun pas"],
  ["successful long passes", "Başarılı uzun pas"],
  ["crosses", "Orta"],
  ["successful crosses", "Başarılı orta"],
  ["accurate crosses", "İsabetli orta"],
  ["aerial duels", "Hava topu mücadelesi"],
  ["successful aerial duels", "Kazanılan hava topu mücadelesi"],
  ["duels", "İkili mücadele"],
  ["successful duels", "Kazanılan ikili mücadele"],
  ["dribbles", "Çalım"],
  ["successful dribbles", "Başarılı çalım"],
  ["tackles", "Top kapma"],
  ["successful tackles", "Başarılı top kapma"],
  ["interceptions", "Araya girme"],
  ["clearances", "Uzaklaştırma"],
  ["attacks", "Hücum"],
  ["dangerous attacks", "Tehlikeli hücum"],
  ["yellow cards", "Sarı kart"],
  ["red cards", "Kırmızı kart"],
  ["cards", "Kart"],
  ["penalties", "Penaltı"],
  ["penalty goals", "Penaltı golü"],
  ["penalty missed", "Kaçan penaltı"],
  ["penalty saves", "Kurtarılan penaltı"],
  ["hit woodwork", "Direkten dönen şut"],
  ["counter attacks", "Kontra atak"],
  ["touches", "Topla buluşma"],
  ["touches in opposition box", "Rakip ceza sahasında topla buluşma"]
]);

export function translateStatisticLabel(name: string) {
  return statisticLabels.get(normalizeStatisticName(name)) ?? name;
}

function normalizeStatisticName(value: string) {
  return value
    .trim()
    .replace(/[‐‑‒–—]/g, "-")
    .replace(/\s+/g, " ")
    .toLowerCase();
}
